"""F-2 with a DECLARED universe: does it discriminate, and where? READ-ONLY, no writes.

`ADR-038` §5/`F-2` asserted a threshold over an undeclared universe ("run the §1.2 harness with
knowledge_time = t; it has to return 61/61"). On the store of `2026-09-12T23:41Z` — backfill only —
that threshold discriminated. With the live collector writing since `23:45:29Z` it SATURATES: a
`STOCK` row fetched ~60 s after its bucket is legitimately knowable at `kt = t`, so BOTH arms read
`61/61` and the falsifier accuses the innocent.

This script measures three universes side by side and prints the DIFFERENTIAL (D1 arm vs the
`§7.1` counterproof) instead of a threshold:

  1. `HOJE-TUDO`      — the whole store, anchored at the newest bucket (what the QA measured).
  2. `SO-BACKFILL`    — rows observed before the live cut (the QA's control; universe FROZEN, it
                        goes to zero after `D15` TRUNCATE + reingest).
  3. `HISTORICO`      — the 61 slots ENDING JUST BEFORE the live collector's first poll. Universe
                        declared by a constant that lives OUTSIDE the column `§7.1` would rewrite,
                        and regenerated by every backfill/reingest.

The counterproof arm is the instrument's own liveness check: it flips to `61/61` exactly when
`observed_at` stops being the fetch instant, which IS `§7.1`.

⛔ A counterproof arm below `61/61` means the universe is EMPTY or too short: that is `F-2` NOT
COMPUTABLE, not `F-2` passed (`ADR-012`, the ambiguous `rc=0`).
"""

import os
import subprocess
import sys
import time
from decimal import Decimal

BACKEND = os.environ["BACKEND_DIR"]
sys.path.insert(0, BACKEND)
from src.modules.sentimento.domain.as_of_accessor import (  # noqa: E402
    BarPolicy,
    Observation,
    ReadPurpose,
    SeriesReadPolicy,
    as_of,
)
from src.modules.sentimento.domain.modeled_availability import (  # noqa: E402
    modeled_available_at_for_endpoint,
)
from src.modules.sentimento.domain.open_interest_catalog import (  # noqa: E402
    binance_open_interest_key,
)
from src.modules.sentimento.domain.provenance import (  # noqa: E402
    AvailabilitySource,
    Provenance,
    SeriesRow,
)

OI = "/futures/data/openInterestHist"
LIVE_START = 1789256473000  # 2026-09-12T23:41:13Z — production deploy; first live poll 23:45:29Z
LIVE_CUT = 1789257900000  # 2026-09-12T23:45:00Z — the QA control's cut, kept for comparability


def q(sql):
    out = subprocess.run(
        ["docker", "exec", "deploy-postgres-1", "psql", "-U", "cripto_strategy",
         "-d", "cripto_strategy", "-At", "-F", "|", "-c", sql],
        capture_output=True, text=True,
    )
    if out.returncode:
        raise SystemExit(out.stderr)
    return [line.split("|") for line in out.stdout.strip().splitlines() if line]


K = binance_open_interest_key(instrument_id="BTCUSDT")
k = K.series_key_id()
raw = q(
    f"select bucket_end,event_time,available_at,ingested_at,observed_at,value_raw from md.series "
    f"where series_key_id='{k}' and symbol='BTCUSDT' and src_label_raw='{OI}' order by bucket_end"
)
if not raw:
    raise SystemExit("ANOMALIA: universo vazio")
NOW = int(time.time() * 1000)


def obs(rows, stamp, shift):
    """`stamp` = the D1 mapper's formula; `shift=True` IS `§7.1` (observed_at := the stamp)."""
    built = []
    for bucket_end, event_time, available_at, ingested_at, observed_at, value_raw in rows:
        bucket_end = int(bucket_end)
        avail = stamp(bucket_end) if stamp else int(available_at)
        source = AvailabilitySource.MODELED if stamp else AvailabilitySource.OBSERVED
        built.append(Observation(
            row=SeriesRow(
                series_key_id=k, symbol="BTCUSDT", source=OI, bucket_end=bucket_end,
                event_time=int(event_time), available_at=avail, availability_source=source,
                ingested_at=int(ingested_at),
                observed_at=(avail if shift else int(observed_at)),
                provenance=Provenance.OBSERVED, src_label_raw=OI, observer_id="o",
                observer_region="r", is_final=True, value_raw=value_raw,
            ),
            value=Decimal(value_raw),
        ))
    return built


def hits(observations, anchor, kt_now, slot=60_000, n=61):
    policy = SeriesReadPolicy(
        asof_max_staleness_ms=600_000, render_max_staleness_ms=600_000,
        bucket_interval_ms=300_000, first_capture_at=None,
    )
    got = 0
    for i in range(n):
        bucket = anchor - (n - 1 - i) * slot
        t = bucket + slot - 1
        read = as_of(
            series=K, symbol="BTCUSDT", t=t, observations=observations, policy=policy,
            bar_policy=BarPolicy.FINAL_ONLY, purpose=ReadPurpose.RENDERING,
            knowledge_time=(NOW if kt_now else t),
        )
        if getattr(read, "value", None) is not None:
            got += 1
    return got


def stamp(bucket_end):
    return modeled_available_at_for_endpoint(endpoint=OI, bucket_end_ms=bucket_end)


backfill_rows = [r for r in raw if int(r[4]) < LIVE_CUT]
historic_anchor = max((int(r[0]) for r in raw if int(r[0]) <= LIVE_START), default=0)
newest = max(int(r[0]) for r in raw)
print(f"linhas: total={len(raw)}  so-backfill={len(backfill_rows)}  ao-vivo={len(raw) - len(backfill_rows)}")
print(f"ancoras: newest={newest}  historico={historic_anchor} (ultimo bucket antes de {LIVE_START})")

d1 = obs(raw, stamp, False)
d1_71 = obs(raw, stamp, True)
cases = [
    ("1 HOJE-TUDO   (store inteiro, ancora no bucket mais novo)", d1, d1_71, newest),
    ("2 SO-BACKFILL (recorte por observed_at < 23:45Z — universo CONGELADO)",
     obs(backfill_rows, stamp, False), obs(backfill_rows, stamp, True),
     max((int(r[0]) for r in backfill_rows), default=0)),
    ("3 HISTORICO   (61 slots ANTES da primeira busca ao vivo — universo DECLARADO)",
     d1, d1_71, historic_anchor),
]
for name, arm_d1, arm_71, anchor in cases:
    if not anchor:
        print(f"\n== {name} == NAO COMPUTAVEL: ancora ausente")
        continue
    print(f"\n== {name} == ancora bucket_end={anchor}")
    for label, slot in (("1min", 60_000), ("5min", 300_000)):
        x = hits(arm_d1, anchor, False, slot=slot)
        y = hits(arm_71, anchor, False, slot=slot)
        verdict = (
            "NAO COMPUTAVEL (contraprova < 61/61)" if y < 61
            else "NAO DISCRIMINA (arms iguais)" if x == y
            else f"DISCRIMINA (delta {y - x})"
        )
        print(f"  F-2 kt=t {label}: D1 {x:>2}/61 | contraprova §7.1 {y:>2}/61 -> {verdict}")
    print(f"  (kt=agora 1min: D1 {hits(arm_d1, anchor, True):>2}/61)")
